package net.hycollege.ljl.pleasedfoof.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.hycollege.ljl.pleasedfood.bean.FoodBean;
import net.hycollege.ljl.pleasedfood.bean.User;

import net.hycollege.ljl.pleasedfoof.greendao.db.FoodBeanDao;
import net.hycollege.ljl.pleasedfoof.greendao.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodBeanDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FoodBeanDao foodBeanDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodBeanDaoConfig = daoConfigMap.get(FoodBeanDao.class).clone();
        foodBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        foodBeanDao = new FoodBeanDao(foodBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(FoodBean.class, foodBeanDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        foodBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FoodBeanDao getFoodBeanDao() {
        return foodBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
